module.exports = {
	entry:'./main.js',
	output:{
		path:__dirname+'/public',
		filename:'mained.js'
	},
	resolve:{
		alias:{
			vue:'vue/dist/vue.js'
		}
	},
	module:{
		loaders:[{
			test:/\.js$/,
			loader:'babel-loader'
		},{
			test:/\.css$/,
			loader:'style-loader!css-loader'
		},{
			test:/\.scss$/,
			loader:'style-loader!css-loader!sass-loader'
		},{
			test:/\.(png|jpg|gif|jpeg)$/,
			loader:'url-loader'
		},{
			test:/\.ttf$/,
			loader:'file-loader'
		},{
			test:/\.vue$/,
			loader:'vue-loader'
		}]
	},
	devServer:{
		contentBase:'./public',
		port:'52061',
		inline:true,
	}
}
